# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 29794991985f30f14fc02ef1a2032d27b9ccf55869c645140fb0ba06cc7482eafc675cb75b19b76e89182d5a8db4f2549efe67abb11ca5ce48457adaef095e32

test:
  secret_key_base: bff3bd16321814161ed8ff2ffec4490fff5073f7030fd0154ed4fbab611a4ca869f7ca02a3a7fbb5e7433e363bc56ab892fcee7c694ff110d7c8a8019e202c20

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
